version: "3.8"

services:
  making-notes:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
        - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
    container_name: making-notes-app
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
    networks:
      - app-network

  dummy-db:
    image: mysql:8.0
    container_name: dummy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dummyroot
      MYSQL_DATABASE: dummydb
      MYSQL_USER: dummyuser
      MYSQL_PASSWORD: dummypassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    profiles: ["db"]

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
