version: "3.8"

services:
  notes-app:
    container_name: notes-app-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_FIREBASE_API_KEY: ${NEXT_PUBLIC_FIREBASE_API_KEY}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${NEXT_PUBLIC_FIREBASE_APP_ID}
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
    networks:
      - internal-network

  mock-database:
    image: mysql:8.0
    container_name: mock-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dummyroot
      MYSQL_DATABASE: dummydb
      MYSQL_USER: dummyuser
      MYSQL_PASSWORD: dummypassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal-network
    profiles:
      - db

volumes:
  mysql-data:

networks:
  internal-network:
    driver: bridge
